version: 2

sources:
  - name: ERP
    database: FEA24_4 
    schema: RAW_ADVENTURE_WORKS 
    tables:
      - name: SALESREASON
      - name: SALESORDERHEADERSALESREASON
      - name: CREDITCARD
      - name: PERSONCREDITCARD
      - name: PERSON